_format_version: "3.0"

plugins:
  - name: prometheus
    config:
      status_code_metrics: true
      latency_metrics: true

services:
  - name: kibana-service
    url: http://kibana:5601
    routes:
      - name: kibana-route
        paths:
          - /kibana

  - name: elasticsearch-service
    url: http://elasticsearch:9200
    routes:
      - name: elasticsearch-route
        paths:
          - /elastic
        strip_path: true

  - name: mock-service
    url: http://httpbin.org/anything
    routes:
      - name: mock-route
        paths:
          - /mock
        strip_path: true


  - name: basis-store-api-service
    url: http://host.docker.internal:7073 
    routes:
      - name: api-store-route
        paths:
          - /api/store 
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - "GET"
                - "POST"
                - "PUT"
                - "DELETE"
                - "OPTIONS"
              headers:
                - "Accept"
                - "Accept-Version"
                - "Content-Length"
                - "Content-MD5"
                - "Content-Type"
                - "Date"
                - "X-Auth-Token"
              exposed_headers:
                - "Content-Type"
                - "Content-Length"
              credentials: true
              max_age: 3600