// <auto-generated />
using Basis.Store.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Basis.Store.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251128183157_CargaInicial")]
    partial class CargaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Basis.Store.Infrastructure.Entities.Catalogo.AssuntoDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodAs");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.ToTable("Assunto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Assunto Estratégico 1"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Assunto Estratégico 2"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Assunto Estratégico 3"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Assunto Estratégico 4"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Assunto Estratégico 5"
                        });
                });

            modelBuilder.Entity("Basis.Store.Infrastructure.Entities.Catalogo.AutorDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodAu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(40)");

                    b.HasKey("Id");

                    b.ToTable("Autor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Autor de Teste 1"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Autor de Teste 2"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Autor de Teste 3"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Autor de Teste 4"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Autor de Teste 5"
                        });
                });

            modelBuilder.Entity("Basis.Store.Infrastructure.Entities.Catalogo.LivroAssuntoDbModel", b =>
                {
                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.Property<int>("AssuntoId")
                        .HasColumnType("int");

                    b.HasKey("LivroId", "AssuntoId");

                    b.HasIndex("AssuntoId");

                    b.ToTable("Livro_Assunto", (string)null);

                    b.HasData(
                        new
                        {
                            LivroId = 1,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 1,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 1,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 1,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 2,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 2,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 2,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 2,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 3,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 4,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 4,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 4,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 4,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 5,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 5,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 6,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 6,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 6,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 7,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 8,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 8,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 8,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 8,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 8,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 9,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 9,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 9,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 10,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 10,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 10,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 10,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 10,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 11,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 11,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 11,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 11,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 12,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 12,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 13,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 13,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 14,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 14,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 14,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 14,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 14,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 15,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 15,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 16,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 16,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 17,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 17,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 17,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 18,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 18,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 18,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 18,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 19,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 20,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 20,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 20,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 20,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 20,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 21,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 21,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 21,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 21,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 22,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 22,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 22,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 22,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 23,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 24,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 24,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 25,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 25,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 25,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 25,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 25,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 26,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 26,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 26,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 26,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 27,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 27,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 27,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 28,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 29,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 29,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 29,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 30,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 30,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 30,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 30,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 30,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 31,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 31,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 31,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 31,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 31,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 32,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 33,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 33,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 33,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 33,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 34,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 34,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 35,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 35,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 35,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 35,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 35,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 36,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 36,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 37,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 38,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 39,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 40,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 40,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 40,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 40,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 41,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 41,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 41,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 41,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 42,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 42,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 42,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 42,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 43,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 43,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 43,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 43,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 44,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 44,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 44,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 44,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 44,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 45,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 45,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 45,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 46,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 47,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 47,
                            AssuntoId = 4
                        },
                        new
                        {
                            LivroId = 48,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 49,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 50,
                            AssuntoId = 3
                        },
                        new
                        {
                            LivroId = 50,
                            AssuntoId = 1
                        },
                        new
                        {
                            LivroId = 50,
                            AssuntoId = 5
                        },
                        new
                        {
                            LivroId = 50,
                            AssuntoId = 2
                        },
                        new
                        {
                            LivroId = 50,
                            AssuntoId = 4
                        });
                });

            modelBuilder.Entity("Basis.Store.Infrastructure.Entities.Catalogo.LivroAutorDbModel", b =>
                {
                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.HasKey("LivroId", "AutorId");

                    b.HasIndex("AutorId");

                    b.ToTable("Livro_Autor", (string)null);

                    b.HasData(
                        new
                        {
                            LivroId = 1,
                            AutorId = 5
                        },
                        new
                        {
                            LivroId = 2,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 3,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 3,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 4,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 5,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 5,
                            AutorId = 5
                        },
                        new
                        {
                            LivroId = 5,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 6,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 6,
                            AutorId = 5
                        },
                        new
                        {
                            LivroId = 7,
                            AutorId = 5
                        },
                        new
                        {
                            LivroId = 7,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 7,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 8,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 8,
                            AutorId = 5
                        },
                        new
                        {
                            LivroId = 9,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 10,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 10,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 11,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 12,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 12,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 13,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 13,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 13,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 14,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 15,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 16,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 16,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 16,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 17,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 17,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 18,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 19,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 19,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 19,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 20,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 20,
                            AutorId = 5
                        },
                        new
                        {
                            LivroId = 20,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 21,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 21,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 21,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 22,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 23,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 23,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 24,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 24,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 25,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 26,
                            AutorId = 5
                        },
                        new
                        {
                            LivroId = 27,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 27,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 27,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 28,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 29,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 30,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 31,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 31,
                            AutorId = 5
                        },
                        new
                        {
                            LivroId = 32,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 32,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 33,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 33,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 33,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 34,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 34,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 35,
                            AutorId = 5
                        },
                        new
                        {
                            LivroId = 35,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 35,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 36,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 36,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 37,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 37,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 37,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 38,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 38,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 38,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 39,
                            AutorId = 5
                        },
                        new
                        {
                            LivroId = 39,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 40,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 40,
                            AutorId = 5
                        },
                        new
                        {
                            LivroId = 40,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 41,
                            AutorId = 5
                        },
                        new
                        {
                            LivroId = 41,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 41,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 42,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 42,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 43,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 43,
                            AutorId = 5
                        },
                        new
                        {
                            LivroId = 44,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 44,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 45,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 45,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 45,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 46,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 47,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 48,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 49,
                            AutorId = 2
                        },
                        new
                        {
                            LivroId = 49,
                            AutorId = 3
                        },
                        new
                        {
                            LivroId = 49,
                            AutorId = 1
                        },
                        new
                        {
                            LivroId = 50,
                            AutorId = 4
                        },
                        new
                        {
                            LivroId = 50,
                            AutorId = 2
                        });
                });

            modelBuilder.Entity("Basis.Store.Infrastructure.Entities.Catalogo.LivroDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cod");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnoPublicacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(4)");

                    b.Property<int>("Edicao")
                        .HasColumnType("int");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnType("VARCHAR(40)");

                    b.Property<decimal>("PrecoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(40)");

                    b.HasKey("Id");

                    b.ToTable("Livro", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoPublicacao = "2021",
                            Edicao = 2,
                            Editora = "Editora Crescimento",
                            PrecoBase = 52.50m,
                            Titulo = "Liderança Fluida 1 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 2,
                            AnoPublicacao = "2022",
                            Edicao = 3,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 55.00m,
                            Titulo = "Liderança Fluida 2 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 3,
                            AnoPublicacao = "2023",
                            Edicao = 1,
                            Editora = "Editora Crescimento",
                            PrecoBase = 57.50m,
                            Titulo = "Liderança Fluida 3 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 4,
                            AnoPublicacao = "2024",
                            Edicao = 2,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 60.00m,
                            Titulo = "Liderança Fluida 4 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 5,
                            AnoPublicacao = "2020",
                            Edicao = 3,
                            Editora = "Editora Crescimento",
                            PrecoBase = 62.50m,
                            Titulo = "O Efeito 5: Inovação Radical em 90 Dias"
                        },
                        new
                        {
                            Id = 6,
                            AnoPublicacao = "2021",
                            Edicao = 1,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 65.00m,
                            Titulo = "Liderança Fluida 6 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 7,
                            AnoPublicacao = "2022",
                            Edicao = 2,
                            Editora = "Editora Crescimento",
                            PrecoBase = 67.50m,
                            Titulo = "Liderança Fluida 7 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 8,
                            AnoPublicacao = "2023",
                            Edicao = 3,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 70.00m,
                            Titulo = "Liderança Fluida 8 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 9,
                            AnoPublicacao = "2024",
                            Edicao = 1,
                            Editora = "Editora Crescimento",
                            PrecoBase = 72.50m,
                            Titulo = "Liderança Fluida 9 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 10,
                            AnoPublicacao = "2020",
                            Edicao = 2,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 75.00m,
                            Titulo = "O Efeito 10: Inovação Radical em 90 Dias"
                        },
                        new
                        {
                            Id = 11,
                            AnoPublicacao = "2021",
                            Edicao = 3,
                            Editora = "Editora Crescimento",
                            PrecoBase = 77.50m,
                            Titulo = "Liderança Fluida 11 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 12,
                            AnoPublicacao = "2022",
                            Edicao = 1,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 80.00m,
                            Titulo = "Liderança Fluida 12 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 13,
                            AnoPublicacao = "2023",
                            Edicao = 2,
                            Editora = "Editora Crescimento",
                            PrecoBase = 82.50m,
                            Titulo = "Liderança Fluida 13 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 14,
                            AnoPublicacao = "2024",
                            Edicao = 3,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 85.00m,
                            Titulo = "Liderança Fluida 14 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 15,
                            AnoPublicacao = "2020",
                            Edicao = 1,
                            Editora = "Editora Crescimento",
                            PrecoBase = 87.50m,
                            Titulo = "O Efeito 15: Inovação Radical em 90 Dias"
                        },
                        new
                        {
                            Id = 16,
                            AnoPublicacao = "2021",
                            Edicao = 2,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 90.00m,
                            Titulo = "Liderança Fluida 16 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 17,
                            AnoPublicacao = "2022",
                            Edicao = 3,
                            Editora = "Editora Crescimento",
                            PrecoBase = 92.50m,
                            Titulo = "Liderança Fluida 17 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 18,
                            AnoPublicacao = "2023",
                            Edicao = 1,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 95.00m,
                            Titulo = "Liderança Fluida 18 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 19,
                            AnoPublicacao = "2024",
                            Edicao = 2,
                            Editora = "Editora Crescimento",
                            PrecoBase = 97.50m,
                            Titulo = "Liderança Fluida 19 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 20,
                            AnoPublicacao = "2020",
                            Edicao = 3,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 100.00m,
                            Titulo = "O Efeito 20: Inovação Radical em 90 Dias"
                        },
                        new
                        {
                            Id = 21,
                            AnoPublicacao = "2021",
                            Edicao = 1,
                            Editora = "Editora Crescimento",
                            PrecoBase = 102.50m,
                            Titulo = "Liderança Fluida 21 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 22,
                            AnoPublicacao = "2022",
                            Edicao = 2,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 105.00m,
                            Titulo = "Liderança Fluida 22 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 23,
                            AnoPublicacao = "2023",
                            Edicao = 3,
                            Editora = "Editora Crescimento",
                            PrecoBase = 107.50m,
                            Titulo = "Liderança Fluida 23 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 24,
                            AnoPublicacao = "2024",
                            Edicao = 1,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 110.00m,
                            Titulo = "Liderança Fluida 24 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 25,
                            AnoPublicacao = "2020",
                            Edicao = 2,
                            Editora = "Editora Crescimento",
                            PrecoBase = 112.50m,
                            Titulo = "O Efeito 25: Inovação Radical em 90 Dias"
                        },
                        new
                        {
                            Id = 26,
                            AnoPublicacao = "2021",
                            Edicao = 3,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 115.00m,
                            Titulo = "Liderança Fluida 26 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 27,
                            AnoPublicacao = "2022",
                            Edicao = 1,
                            Editora = "Editora Crescimento",
                            PrecoBase = 117.50m,
                            Titulo = "Liderança Fluida 27 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 28,
                            AnoPublicacao = "2023",
                            Edicao = 2,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 120.00m,
                            Titulo = "Liderança Fluida 28 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 29,
                            AnoPublicacao = "2024",
                            Edicao = 3,
                            Editora = "Editora Crescimento",
                            PrecoBase = 122.50m,
                            Titulo = "Liderança Fluida 29 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 30,
                            AnoPublicacao = "2020",
                            Edicao = 1,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 125.00m,
                            Titulo = "O Efeito 30: Inovação Radical em 90 Dias"
                        },
                        new
                        {
                            Id = 31,
                            AnoPublicacao = "2021",
                            Edicao = 2,
                            Editora = "Editora Crescimento",
                            PrecoBase = 127.50m,
                            Titulo = "Liderança Fluida 31 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 32,
                            AnoPublicacao = "2022",
                            Edicao = 3,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 130.00m,
                            Titulo = "Liderança Fluida 32 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 33,
                            AnoPublicacao = "2023",
                            Edicao = 1,
                            Editora = "Editora Crescimento",
                            PrecoBase = 132.50m,
                            Titulo = "Liderança Fluida 33 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 34,
                            AnoPublicacao = "2024",
                            Edicao = 2,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 135.00m,
                            Titulo = "Liderança Fluida 34 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 35,
                            AnoPublicacao = "2020",
                            Edicao = 3,
                            Editora = "Editora Crescimento",
                            PrecoBase = 137.50m,
                            Titulo = "O Efeito 35: Inovação Radical em 90 Dias"
                        },
                        new
                        {
                            Id = 36,
                            AnoPublicacao = "2021",
                            Edicao = 1,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 140.00m,
                            Titulo = "Liderança Fluida 36 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 37,
                            AnoPublicacao = "2022",
                            Edicao = 2,
                            Editora = "Editora Crescimento",
                            PrecoBase = 142.50m,
                            Titulo = "Liderança Fluida 37 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 38,
                            AnoPublicacao = "2023",
                            Edicao = 3,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 145.00m,
                            Titulo = "Liderança Fluida 38 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 39,
                            AnoPublicacao = "2024",
                            Edicao = 1,
                            Editora = "Editora Crescimento",
                            PrecoBase = 147.50m,
                            Titulo = "Liderança Fluida 39 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 40,
                            AnoPublicacao = "2020",
                            Edicao = 2,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 150.00m,
                            Titulo = "O Efeito 40: Inovação Radical em 90 Dias"
                        },
                        new
                        {
                            Id = 41,
                            AnoPublicacao = "2021",
                            Edicao = 3,
                            Editora = "Editora Crescimento",
                            PrecoBase = 152.50m,
                            Titulo = "Liderança Fluida 41 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 42,
                            AnoPublicacao = "2022",
                            Edicao = 1,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 155.00m,
                            Titulo = "Liderança Fluida 42 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 43,
                            AnoPublicacao = "2023",
                            Edicao = 2,
                            Editora = "Editora Crescimento",
                            PrecoBase = 157.50m,
                            Titulo = "Liderança Fluida 43 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 44,
                            AnoPublicacao = "2024",
                            Edicao = 3,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 160.00m,
                            Titulo = "Liderança Fluida 44 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 45,
                            AnoPublicacao = "2020",
                            Edicao = 1,
                            Editora = "Editora Crescimento",
                            PrecoBase = 162.50m,
                            Titulo = "O Efeito 45: Inovação Radical em 90 Dias"
                        },
                        new
                        {
                            Id = 46,
                            AnoPublicacao = "2021",
                            Edicao = 2,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 165.00m,
                            Titulo = "Liderança Fluida 46 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 47,
                            AnoPublicacao = "2022",
                            Edicao = 3,
                            Editora = "Editora Crescimento",
                            PrecoBase = 167.50m,
                            Titulo = "Liderança Fluida 47 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 48,
                            AnoPublicacao = "2023",
                            Edicao = 1,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 170.00m,
                            Titulo = "Liderança Fluida 48 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 49,
                            AnoPublicacao = "2024",
                            Edicao = 2,
                            Editora = "Editora Crescimento",
                            PrecoBase = 172.50m,
                            Titulo = "Liderança Fluida 49 - Manifesto da Adaptabilidade"
                        },
                        new
                        {
                            Id = 50,
                            AnoPublicacao = "2020",
                            Edicao = 3,
                            Editora = "Editora Vanguarda",
                            PrecoBase = 175.00m,
                            Titulo = "O Efeito 50: Inovação Radical em 90 Dias"
                        });
                });

            modelBuilder.Entity("Basis.Store.Infrastructure.Entities.Catalogo.LivroAssuntoDbModel", b =>
                {
                    b.HasOne("Basis.Store.Infrastructure.Entities.Catalogo.AssuntoDbModel", "Assunto")
                        .WithMany("LivroAssuntos")
                        .HasForeignKey("AssuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Basis.Store.Infrastructure.Entities.Catalogo.LivroDbModel", "Livro")
                        .WithMany("LivroAssuntos")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assunto");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Basis.Store.Infrastructure.Entities.Catalogo.LivroAutorDbModel", b =>
                {
                    b.HasOne("Basis.Store.Infrastructure.Entities.Catalogo.AutorDbModel", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Basis.Store.Infrastructure.Entities.Catalogo.LivroDbModel", "Livro")
                        .WithMany("LivroAutores")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Basis.Store.Infrastructure.Entities.Catalogo.AssuntoDbModel", b =>
                {
                    b.Navigation("LivroAssuntos");
                });

            modelBuilder.Entity("Basis.Store.Infrastructure.Entities.Catalogo.LivroDbModel", b =>
                {
                    b.Navigation("LivroAssuntos");

                    b.Navigation("LivroAutores");
                });
#pragma warning restore 612, 618
        }
    }
}
